# Generated by Django 4.1.4 on 2023-06-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("agent_id", models.AutoField(primary_key=True, serialize=False)),
                ("queue", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("issue_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("problem", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Mechanic",
            fields=[
                ("mechanic_id", models.AutoField(primary_key=True, serialize=False)),
                ("availability", models.BooleanField(default=True)),
            ],
        ),
    ]
