# Generated by Django 4.1.4 on 2023-06-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="time",
            field=models.CharField(max_length=100),
        ),
    ]
