# Generated by Django 4.1.4 on 2023-06-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_issue_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent2",
            fields=[
                ("agent_id", models.AutoField(primary_key=True, serialize=False)),
                ("queue", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Agent3",
            fields=[
                ("agent_id", models.AutoField(primary_key=True, serialize=False)),
                ("queue", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Agent4",
            fields=[
                ("agent_id", models.AutoField(primary_key=True, serialize=False)),
                ("queue", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Agent5",
            fields=[
                ("agent_id", models.AutoField(primary_key=True, serialize=False)),
                ("queue", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name="Agent",
            new_name="Agent1",
        ),
    ]
