# Generated by Django 4.1.4 on 2023-06-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_agent2_agent3_agent4_agent5_rename_agent_agent1"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent1",
            name="user_id",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name="agent2",
            name="user_id",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name="agent3",
            name="user_id",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name="agent4",
            name="user_id",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name="agent5",
            name="user_id",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name="agent1",
            name="queue",
            field=models.CharField(default="Inque", max_length=100),
        ),
        migrations.AlterField(
            model_name="agent2",
            name="queue",
            field=models.CharField(default="Inque", max_length=100),
        ),
        migrations.AlterField(
            model_name="agent3",
            name="queue",
            field=models.CharField(default="Inque", max_length=100),
        ),
        migrations.AlterField(
            model_name="agent4",
            name="queue",
            field=models.CharField(default="Inque", max_length=100),
        ),
        migrations.AlterField(
            model_name="agent5",
            name="queue",
            field=models.CharField(default="Inque", max_length=100),
        ),
    ]
