# Generated by Django 4.1.4 on 2023-06-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_agent1_queue_alter_agent2_queue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="user_name",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name="agent1",
            name="queue",
            field=models.CharField(
                choices=[("1", "inque"), ("2", "assigned"), ("3", "dispatched")],
                default="inque",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="agent2",
            name="queue",
            field=models.CharField(
                choices=[("1", "inque"), ("2", "assigned"), ("3", "dispatched")],
                default="inque",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="agent3",
            name="queue",
            field=models.CharField(
                choices=[("1", "inque"), ("2", "assigned"), ("3", "dispatched")],
                default="inque",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="agent4",
            name="queue",
            field=models.CharField(
                choices=[("1", "inque"), ("2", "assigned"), ("3", "dispatched")],
                default="inque",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="agent5",
            name="queue",
            field=models.CharField(
                choices=[("1", "inque"), ("2", "assigned"), ("3", "dispatched")],
                default="inque",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="location",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name="issue",
            name="problem",
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[("1", "inque"), ("2", "assigned"), ("3", "dispatched")],
                default="inque",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="time",
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name="issue",
            name="user_id",
            field=models.CharField(default=0, max_length=100),
        ),
    ]
